apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: API_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secrets
              key: api_id
        - name: API_HASH
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secrets
              key: api_hash
        - name: SESSION
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secrets
              key: session
