apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  api_id: {{ .Values.env.api_id | quote }}
  api_hash: {{ .Values.env.api_hash | quote }}
  session: {{ .Values.env.session | quote }}
